ALTER TABLE users ADD COLUMN IF NOT EXISTS org_id VARCHAR(64) REFERENCES organizations(id) ON DELETE SET NULL;

ALTER TABLE providers ADD COLUMN IF NOT EXISTS org_id VARCHAR(64) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE providers ADD COLUMN IF NOT EXISTS workspace_id VARCHAR(64) REFERENCES workspaces(id) ON DELETE CASCADE;

ALTER TABLE gateway_api_keys ADD COLUMN IF NOT EXISTS org_id VARCHAR(64) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE gateway_api_keys ADD COLUMN IF NOT EXISTS workspace_id VARCHAR(64) REFERENCES workspaces(id) ON DELETE CASCADE;
ALTER TABLE gateway_api_keys ADD COLUMN IF NOT EXISTS project_id VARCHAR(64) REFERENCES projects(id) ON DELETE CASCADE;

ALTER TABLE agents ADD COLUMN IF NOT EXISTS org_id VARCHAR(64) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS workspace_id VARCHAR(64) REFERENCES workspaces(id) ON DELETE CASCADE;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS project_id VARCHAR(64) REFERENCES projects(id) ON DELETE CASCADE;

ALTER TABLE tools ADD COLUMN IF NOT EXISTS org_id VARCHAR(64) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE tools ADD COLUMN IF NOT EXISTS workspace_id VARCHAR(64) REFERENCES workspaces(id) ON DELETE CASCADE;

ALTER TABLE resources ADD COLUMN IF NOT EXISTS org_id VARCHAR(64) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE resources ADD COLUMN IF NOT EXISTS workspace_id VARCHAR(64) REFERENCES workspaces(id) ON DELETE CASCADE;

ALTER TABLE mcp_servers ADD COLUMN IF NOT EXISTS org_id VARCHAR(64) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE mcp_servers ADD COLUMN IF NOT EXISTS workspace_id VARCHAR(64) REFERENCES workspaces(id) ON DELETE CASCADE;

ALTER TABLE governance_policies ADD COLUMN IF NOT EXISTS org_id VARCHAR(64) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE governance_policies ADD COLUMN IF NOT EXISTS workspace_id VARCHAR(64) REFERENCES workspaces(id) ON DELETE CASCADE;

ALTER TABLE request_logs ADD COLUMN IF NOT EXISTS org_id VARCHAR(64);
ALTER TABLE request_logs ADD COLUMN IF NOT EXISTS workspace_id VARCHAR(64);
ALTER TABLE request_logs ADD COLUMN IF NOT EXISTS project_id VARCHAR(64);
