ALTER TABLE request_logs 
  ADD COLUMN IF NOT EXISTS client_ip VARCHAR(45),
  ADD COLUMN IF NOT EXISTS user_agent TEXT,
  ADD COLUMN IF NOT EXISTS client_app VARCHAR(50),
  ADD COLUMN IF NOT EXISTS is_stream BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS ttft_ms INT DEFAULT 0;
